version: '3.3'
services:
  dev:
    image: openjdk:17
    links:
      - db
      - redis
    command: echo 'dev environment started'

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'mars-gradle-dgs'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mars-gradle-dgs-mysql:/var/lib/mysql

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mars-gradle-dgs-mysql: